export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const ADD_FOLDER = "ADD_FOLDER";
export const REMOVE_FOLDERS = "REMOVE_FOLDERS";
export const SET_FOLDERS = "SET_FOLDERS";
export const SET_ACTIVE_FOLDER = "SET_ACTIVE_FOLDER";
export const SET_OPEN_FOLDERS = "SET_OPEN_FOLDERS";
export const SET_FOLDER = "SET_FOLDER";

export const ADD_NOTE = "ADD_NOTE";
export const REMOVE_NOTES = "REMOVE_NOTES";
export const SET_FETCHED_NOTES = "SET_FETCHED_NOTES";
export const SET_UPDATED_NOTES = "SET_UPDATED_NOTES";
export const SET_ACTIVE_NOTE = "SET_ACTIVE_NOTE";
export const SET_NOTE = "SET_NOTE";

export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT";
export const CLEAR_SEARCH_RESULT = "CLEAR_SEARCH_RESULT";

export const OPEN_NOTE_DETAILS = "OPEN_NOTE_DETAILS";
export const CLOSE_NOTE_DETAILS = "CLOSE_NOTE_DETAILS";
